### ISSUE TITLE
Cannot Setup Lunalytics Via Docker

### ISSUE THREAD

**Issue by MrJupiter** [KSJaay/Lunalytics#95]
I ve just deployed via docker-compose :
```
services:
  lunalytics:
    image: ksjaay/lunalytics:latest
    container_name: lunalytics
    volumes:
      - /mnt/docker/lunalytics/data:/app/data
      - /mnt/docker/lunalytics/logs:/app/logs
    ports:
      - '2308:2308'
    networks:
      - frontend

networks:
  frontend:
    external: true
```
I cannot choose 'Basic Setup' and also when I choose 'Advanced Setup', I got blocked at JWT Secret page:

![Image](https://github.com/user-attachments/assets/2ae4afd6-821b-4da4-9e60-86543b4cea4a)

![Image](https://github.com/user-attachments/assets/1c7d8496-8930-477b-b74d-8c771ed2e1e7)
